# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Action Deploy To Eb - Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install

      - name: Run Test
        run: yarn test --forceExit

      - name: Show Coverage
        run: yarn test:coverage  --forceExit

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Generate deployment package
        run: zip -r deploy.zip src/ *.js *.json yarn.lock

      - name: Set VERSION_LABEL_TIMESTAMP
        run: |
          VERSION_LABEL_TIMESTAMP=$(date +'%H%M%S%d%m%Y')
          echo $VERSION_LABEL_TIMESTAMP

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.ENVIRONMENT_NAME }}
          version_label: $(echo $VERSION_LABEL_TIMESTAMP)
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
